version: "3.9"
services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    restart: always
    volumes:
      - ollama:/root/.ollama
  open-webui:
    build:
      context: .
      args:
        OLLAMA_API_BASE_URL: "/ollama/api"
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OLLAMA_WEBUI_PORT-3000}:8080
    environment:
      - "OLLAMA_API_BASE_URL=http://ollama:11434/api"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
volumes:
  open-webui: {}
  ollama: {}